import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Providers from "./components/Providers";
import Appbar from "./components/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const img = "https://img.freepik.com/premium-photo/wooden-cutting-board-with-garlic-tomatoes-basil-peppercorns-cream-white-background_1222783-12511.jpg?w=1060"
  //const img = "https://img.freepik.com/free-photo/ingredients-cabbage-carrot-pie-cabbage-carrots-eggs-flour-milk-butter-spices-white-background_127032-2819.jpg";
  //const img = "https://img.freepik.com/free-photo/spices-tomatoes-near-spaghetti-garlic_23-2147849739.jpg?size=626&ext=jpg&ga=GA1.1.1791467760.1725986295&semt=ais_hybrid"
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-screen`}>
        <div
          className="h-screen w-screen bg-cover bg-center overflow-auto"
          style={{
            backgroundImage: `url(${img})`,
          }}
        >
          <Providers>
          <Appbar />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
